### ISSUE TITLE
Can not load app from online app in ZWAVE SMART HOME

### ISSUE THREAD

**Issue by LenMaroko** [ralphwetzel/Bridge4KT#1]
Get error
Smart Home UI Error
Failed to install the App

CAN NOT LOAD ANY APP :(

**Comment by ralphwetzel** [comment]
This is - most probably - the same issue already discussed in Z-Wave-Me/zwave-smarthome#275, not related to this plugin. Please verify.
Give me a note, if you still encounter problems after application of the preliminary fix...

**Comment by LenMaroko** [comment]
Ok, and thanks 🙏 for responding. 

Best regards from Lennart


Lennart Maroko                                                  
Civilingenjör / MScEE

Maroko Hightech Installatzies
m: +46 (0) 70 339 4600
WhatsApp: +46 70 339 4600
e: hightech@maroko.se
a: Timmermansgränd 3, 118 65 Stockholm, Sweden
